version: '3.8'

services:
  api:
    build: .
    container_name: p2p-video-api
    restart: unless-stopped
    expose:
      - "6000"  
    environment:
      - NODE_ENV=production
    networks:
      - p2p-network
networks:
  p2p-network:
    driver: bridge
