version: '3.8'

services:
  api:
    build: .
    container_name: p2p-video-api
    restart: unless-stopped
    expose:
      - "3000"  # Exposto apenas para outros containers
    environment:
      - NODE_ENV=production
    networks:
      - p2p-network

  nginx:
    image: nginx:alpine
    container_name: p2p-nginx
    ports:
      - "80:80"
      - "443:443"  # Para futura configuração HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/conf.d
    depends_on:
      - api
    networks:
      - p2p-network

networks:
  p2p-network:
    driver: bridge
